# Generated by Django 5.1.3 on 2024-12-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special_offer',
            field=models.BooleanField(default=False),
        ),
    ]
